services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: citypass-ldap
    environment:
      LDAP_ORGANISATION: "CityPass"
      LDAP_DOMAIN: "citypass.local"
      LDAP_ADMIN_PASSWORD: "admin"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./ldap/seed:/container/service/slapd/assets/config/bootstrap/ldif/custom
    command: --copy-service

  postgres:
    image: postgres:16-alpine
    container_name: citypass-db
    environment:
      POSTGRES_DB: login_federado
      POSTGRES_USER: citypass
      POSTGRES_PASSWORD: citypass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: citypass-login
    ports:
      - "8081:8082"
    environment:
      LDAP_ADMIN_PASSWORD: "admin"
      DB_USERNAME: "citypass"
      DB_PASSWORD: "citypass"
      SPRING_LDAP_URLS: "ldap://openldap:389"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/login_federado"
      ANOMALY_SERVICE_URL: "http://anomaly-detection:8000"   
    depends_on:
      - openldap
      - postgres
      - anomaly-detection  

  anomaly-detection:
    build: ../anomaly-detection
    container_name: citypass-anomaly-detection
    ports:
      - "8000:8000"
    environment:
      ANOMALY_DB_URL: "postgresql://citypass:citypass@postgres:5432/login_federado"
    depends_on:
      - postgres
volumes:
  pgdata:
